<?php

namespace App\Models;

use App\Scopes\EmpresaUserScope;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
/** Representa una Empresa en la base de datos.
 *
 * @property int            $id
 * @property int            $user_id
 * @property string         $nombre
 * @property string         $telefono
 * @property Carbon         $created_at
 * @property Carbon         $updated_at
 * @package App\Models
 */

class Empresa extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     *  @var string[]
     */
    protected $fillable = [
        'user_id',
        'nombre',
        'telefono',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new EmpresaUserScope());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function clientes()
    {
        return $this->hasMany(Cliente::class,'empresa_id');
    }
}
